### ISSUE TITLE
Add general contribution guidelines

### ISSUE THREAD

**Issue by Ishika2** [dscmsit/Problem-Solving-in-any-Language#4]
I noticed that there are no contribution guidelines given in the Readme.md file. For a newcomer to an open source community, it's difficult to contribute to open source without following the steps.
So, I would like to add contribution guidelines with proper commands and steps to this repo, which will be helpful for beginners.

Thanks and Regards
Ishika Punchariya

**Comment by gdscMsit** [comment]
Done!!!
